### ISSUE TITLE
Iphone 5S Bug.

### ISSUE THREAD

**Issue by Gargo** [saqibomer/Loadmation#2]
Just ran on iPhone 5s simulator... It looks like a spinning tennis ball, not "progress"

**Comment by saqibomer** [comment]
It is a loading animation. Adding more options in coming days.

**Comment by Gargo** [comment]
@saqibomer on iPhone 5s it even doesn't look like your screenshots

**Comment by Gargo** [comment]
@saqibomer and? closed bug but didn't fix it:
https://ibb.co/ecCRxG

**Comment by saqibomer** [comment]
Issue has been fixed. ` pod update Loadmation` to install latest release (0.0.9)
